### ISSUE TITLE
Ignore missing reference does not work

### ISSUE THREAD

**Issue by MartaUch** [Azure-Player/azure.datafactory.tools#370]
Hello,
It seems that ignoring missing reference feature does not work as suppose to.
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/28823253/2876daf5-5bd9-4db1-9822-4355d128ae22)
![image](https://github.com/Azure-Player/azure.datafactory.tools/assets/28823253/8f950223-84b6-4553-b2dd-4df2c0625869)
There is a warning indeed, but later error is still raised. Am I missing something?

Kind Regards
Marta

**Comment by NowinskiK** [comment]
All works as expected.
The first message (warning `ADFT0006`) explains situation before deployment:
1) There is reference between objects.
2) Referenced object doesn't exist in local code
3) User decides to ignore such fact (flag `IgnoreLackOfReferencedObject` = `true`)
4) Deployment failed due to missing (referenced) object in ADF service
In other words - if one uses flag `IgnoreLackOfReferencedObject` then it's they responsibility to make sure all referenced objects exist in target ADF service. Otherwise the deployment may fail.
